/- Typed local proofs and exact singleton layout binding for generated byte-pair proposals.
   Requires the fixed Golf model and height-only GolfGeneratedFault abstraction. -/
namespace GolfGenericWindow
open GolfLayout

-- Proposal grammar/profile are owned by GenericWindowProfile.
structure GenericLocal (site : Site) (required : Nat) (delta : Int)
 (peak beforeOps afterOps : Nat) where
 requiredExact : site.requiredStack = required
 feasible : required + peak ≤ 1024
 nonemptyBefore : site.before ≠ []
 nonemptyAfter : site.after ≠ []
 sameLength : site.before.length = site.after.length
 beforeBytes : site.before.all (fun b => b < 256) = true
 afterBytes : site.after.all (fun b => b < 256) = true
 beforeSupported : supported site.before = true
 afterSupported : supported site.after = true
 beforeComplete : GolfComposition.Complete site.before beforeOps
 afterComplete : GolfComposition.Complete site.after afterOps
 beforeProfile : GolfGenericWindow.profile site.before = some (required,delta,peak)
 afterProfile : GolfGenericWindow.profile site.after = some (required,delta,peak)
 -- Complete returned stack, not merely one arithmetic expression.
 output : List Golf.Word → Golf.Word → Golf.Word → List Golf.Word
 success : ∀ stack x y, required ≤ stack.length → stack.length + peak ≤ 1024 →
   GolfBounded.run (site.before.length+1) site.before stack x y = some (output stack x y) ∧
   GolfBounded.run (site.after.length+1) site.after stack x y = some (output stack x y)
 underflow : ∀ stack x y, stack.length < required →
   GolfBounded.run (site.before.length+1) site.before stack x y = none ∧
   GolfBounded.run (site.after.length+1) site.after stack x y = none
 overflow : ∀ stack x y, 1024 < stack.length + peak →
   GolfBounded.run (site.before.length+1) site.before stack x y = none ∧
   GolfBounded.run (site.after.length+1) site.after stack x y = none
 allHeight : ∀ stack x y,
   GolfBounded.run (site.before.length+1) site.before stack x y =
   GolfBounded.run (site.after.length+1) site.after stack x y
 context : GolfComposition.ContextEquivalent site.before site.after
 gas : GolfGas.Improvement site.before site.after
 -- This is a sufficient-gas height-only abstraction, NOT revm correspondence.
 faultClasses : (List.range 1025).all (fun h => decide
   (GolfGeneratedFault.run (site.before.length+1) site.before h =
    GolfGeneratedFault.run (site.after.length+1) site.after h)) = true

abbrev Row := Nat × Nat × Bool
def inSite (site : Site) (pc : Nat) : Bool :=
 site.pc ≤ pc && pc < site.pc + site.before.length
def exterior (site : Site) (rows : List Row) := rows.filter (fun row => !inSite site row.1)
def jumps (rows : List Row) := (rows.filter (fun row => row.2.2)).map (fun row => row.1)
def noInterior (site : Site) (rows : List Row) : Bool :=
 rows.all (fun row => !row.2.2 || !(site.pc < row.1 && row.1 < site.pc+site.before.length))
def disjoint (start size otherStart otherSize : Nat) : Bool :=
 size == 0 || otherSize == 0 || start+size ≤ otherStart || otherStart+otherSize ≤ start

def protectedCopies (site : Site) (copies : List CodeCopy) : Bool :=
 copies.all (fun copy =>
   disjoint site.pc site.before.length copy.source copy.length &&
   disjoint site.pc site.before.length copy.prefixStart (copy.pc+1-copy.prefixStart))

-- Only this singleton certified site can remove rows from exterior comparison.
-- Copy enumeration and admissible execution entry remain trusted runtime gates.
abbrev StructuralChecks (original candidate : List Nat) (site : Site)
 (copies : List CodeCopy) : Prop :=
 original.all (fun b => b<256) = true ∧
 candidate.all (fun b => b<256) = true ∧
 applySites original [site] = some candidate ∧
 original.length = candidate.length ∧
 aligned [site] ((scan original).map (fun row => row.1) ++ [original.length]) = true ∧
 aligned [site] ((scan candidate).map (fun row => row.1) ++ [candidate.length]) = true ∧
 exterior site (scan original) = exterior site (scan candidate) ∧
 jumps (scan original) = jumps (scan candidate) ∧
 noInterior site (scan original) = true ∧
 noInterior site (scan candidate) = true ∧
 copies.all (fun copy =>
   ((scan original).map (fun row => row.1)).contains copy.prefixStart &&
   ((scan candidate).map (fun row => row.1)).contains copy.prefixStart &&
   copyPrefix original copy && copyPrefix candidate copy &&
   (original.drop copy.prefixStart).take (copy.pc+1-copy.prefixStart) ==
     (candidate.drop copy.prefixStart).take (copy.pc+1-copy.prefixStart)) = true ∧
 copies.all (fun copy => copy.source+copy.length ≤ original.length &&
   copy.source+copy.length ≤ candidate.length) = true ∧
 copies.all (fun copy => (original.drop copy.source).take copy.length ==
   (candidate.drop copy.source).take copy.length) = true ∧
 protectedCopies site copies = true

structure GenericWindowArtifact (original candidate : List Nat) (site : Site)
 (copies : List CodeCopy) (required : Nat) (delta : Int) (peak beforeOps afterOps : Nat) where
 localProof : GenericLocal site required delta peak beforeOps afterOps
 structural : StructuralChecks original candidate site copies

-- Explicit bridge to existing literal-read certificate, not a weaker substitute.
theorem copies_valid {original candidate site copies}
 (h : StructuralChecks original candidate site copies) : CodeCopyArtifact original candidate copies := by
 rcases h with ⟨_,_,_,_,_,_,_,_,_,_,prefixes,bounds,bytes,_⟩
 exact ⟨prefixes,bounds,bytes⟩
end GolfGenericWindow
